# -*- coding: utf-8 -*-
"""HTML Quick Styler .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TgQPuU660hJMHfR0Ra-l26dWjnFVWO90
"""

!pip install gradio transformers accelerate torch

!pip install sentencepiece

!pip install gradio transformers accelerate torch

model_id = "ibm-granite/granite-3.3-2b-instruct"

from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

model_id = "ibm-granite/granite-3.3-2b-instruct"

tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    device_map="auto",
    torch_dtype="auto"
)

print(f"Model {model_id} loaded successfully.")

from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

model_name = "ibm-granite/granite-3.3-2b-instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16,
    device_map="auto"
)

def generate_text(prompt):
    inputs = tokenizer(prompt, return_tensors="pt").to("cuda")
    outputs = model.generate(**inputs, max_new_tokens=300)
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

print("Model Loaded Successfully ✅")

class ColorPaletteGenerator:
    def __init__(self):
        self.palettes = {
            "modern": {
                "primary": "#4F46E5",
                "secondary": "#6366F1",
                "accent": "#22D3EE",
                "background": "#0F172A",
                "surface": "#1E293B",
                "text_primary": "#F8FAFC",
                "text_secondary": "#CBD5E1",
                "border": "#334155"
            },
            "vibrant": {
                "primary": "#FF6B6B",
                "secondary": "#FFD93D",
                "accent": "#6BCB77",
                "background": "#1A1A2E",
                "surface": "#16213E",
                "text_primary": "#FFFFFF",
                "text_secondary": "#EAEAEA",
                "border": "#0F3460"
            },
            "ocean": {
                "primary": "#0077B6",
                "secondary": "#0096C7",
                "accent": "#00B4D8",
                "background": "#03045E",
                "surface": "#023E8A",
                "text_primary": "#CAF0F8",
                "text_secondary": "#ADE8F4",
                "border": "#0077B6"
            }
        }

    def get_palette(self, style):
        return self.palettes.get(style, self.palettes["modern"])

class HTMLPageBuilder:

    def generate_meta_tags(self, title):
        return f"""
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{title}</title>
        <meta property="og:title" content="{title}">
        <meta name="twitter:card" content="summary_large_image">
        """

    def build_hero_section(self, title):
        return f"""
        <section class="hero">
            <h1>{title}</h1>
            <p>Welcome to our modern AI generated website</p>
            <button>Get Started</button>
        </section>
        """

    def build_footer(self):
        return """
        <footer>
            <p>© 2026 HTML Quick-Styler. All Rights Reserved.</p>
        </footer>
        """

    def build_page(self, title):
        meta = self.generate_meta_tags(title)
        hero = self.build_hero_section(title)
        footer = self.build_footer()

        return f"""
        <!DOCTYPE html>
        <html>
        <head>
        {meta}
        </head>
        <body>
        {hero}
        {footer}
        </body>
        </html>
        """

def generate_css(colors):
    return f"""
    :root {{
        --primary: {colors['primary']};
        --secondary: {colors['secondary']};
        --accent: {colors['accent']};
        --background: {colors['background']};
        --surface: {colors['surface']};
        --text-primary: {colors['text_primary']};
        --text-secondary: {colors['text_secondary']};
    }}

    body {{
        margin: 0;
        font-family: Arial, sans-serif;
        background: var(--background);
        color: var(--text-primary);
    }}

    .hero {{
        text-align: center;
        padding: 100px 20px;
        background: linear-gradient(135deg, var(--primary), var(--secondary));
    }}

    button {{
        padding: 12px 24px;
        background: var(--accent);
        border: none;
        border-radius: 5px;
        cursor: pointer;
        transition: 0.3s;
    }}

    button:hover {{
        opacity: 0.8;
    }}

    footer {{
        text-align: center;
        padding: 20px;
        background: var(--surface);
    }}
    """

import gradio as gr

# --- Redefining dependencies to ensure they exist in the current session ---
class ColorPaletteGenerator:
    def __init__(self):
        self.palettes = {
            "modern": {"primary": "#4F46E5", "secondary": "#6366F1", "accent": "#22D3EE", "background": "#0F172A", "surface": "#1E293B", "text_primary": "#F8FAFC", "text_secondary": "#CBD5E1", "border": "#334155"},
            "vibrant": {"primary": "#FF6B6B", "secondary": "#FFD93D", "accent": "#6BCB77", "background": "#1A1A2E", "surface": "#16213E", "text_primary": "#FFFFFF", "text_secondary": "#EAEAEA", "border": "#0F3460"},
            "ocean": {"primary": "#0077B6", "secondary": "#0096C7", "accent": "#00B4D8", "background": "#03045E", "surface": "#023E8A", "text_primary": "#CAF0F8", "text_secondary": "#ADE8F4", "border": "#0077B6"}
        }
    def get_palette(self, style):
        return self.palettes.get(style, self.palettes["modern"])

class HTMLPageBuilder:
    def build_page(self, title):
        return f"<!DOCTYPE html><html><head><title>{title}</title></head><body><section class='hero'><h1>{title}</h1><button>Get Started</button></section></body></html>"

def generate_css(colors):
    return f":root {{ --primary: {colors['primary']}; --accent: {colors['accent']}; --background: {colors['background']}; }} body {{ background: var(--background); color: white; }} .hero {{ padding: 100px; background: var(--primary); }}"

# --- Main App Logic ---
palette_generator = ColorPaletteGenerator()
page_builder = HTMLPageBuilder()

def generate_website(title, style):
    colors = palette_generator.get_palette(style)
    html = page_builder.build_page(title)
    css = generate_css(colors)
    return f"<style>{css}</style>" + html

with gr.Blocks() as demo:
    gr.Markdown("# HTML Quick-Styler")
    title = gr.Textbox(label="Website Title")
    style = gr.Dropdown(["modern", "vibrant", "ocean"], label="Color Style")
    output = gr.Code(language="html")
    btn = gr.Button("Generate")
    btn.click(generate_website, inputs=[title, style], outputs=output)

demo.launch(share=True)

demo.launch(share=True)

import os
from google.colab import drive

# Check if drive is already mounted to avoid unnecessary prompts
if not os.path.exists('/content/drive'):
    try:
        drive.mount('/content/drive', force_remount=True)
        print("Drive mounted successfully!")
    except Exception as e:
        print(f"Failed to mount Drive: {e}")
        print("Please ensure you click 'Connect to Google Drive' in the prompt above.")
else:
    print("Drive already mounted.")

prompt = "Explain the importance of open-source AI in two sentences."
inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

output = model.generate(**inputs, max_new_tokens=100)
response = tokenizer.decode(output[0], skip_special_tokens=True)

print(f"Response from Granite:\n{response}")